remote_theme: pmarsceill/just-the-docs

# Aux links for the upper right navigation
aux_links:
  "Edit on GitHub":
    - "//github.com/magentaworks/hankookilbo"

# Footer content appears at the bottom of every page's main content
footer_content: "Copyright &copy; 2020 Magentaworks. Distributed by an <a href=\"https://github.com/pmarsceill/just-the-docs/tree/master/LICENSE.txt\">MIT license.</a>"
