remote_theme: pmarsceill/just-the-docs

# Footer content appears at the bottom of every page's main content
footer_content: "Copyright &copy; 2020 Magentaworks. Distributed by an <a href=\"https://github.com/pmarsceill/just-the-docs/tree/master/LICENSE.txt\">MIT license.</a>"
